### ISSUE TITLE
Create a cross-browser supported blurred-glass menu bar.

### ISSUE THREAD

**Issue by irffanasiff** [demonicirfan/Hackrack.in#1]
Create a menu bar with blurred glass effect that is supported on all the browsers ( specially firefox ). [Refer to this article ](https://luisball.com/corss-browser-glass-navbar/)

## Demo

https://user-images.githubusercontent.com/74172466/146571859-e946ccda-5894-4276-814e-bb9e32808464.mp4

You can also check it out at [here](https://hackrack.in). Also try if you can make it responsive like this. The article mentioned above may help you.

**Comment by kady-z** [comment]
Sir I would like to work on this. Please assign me this.
Thank you!

**Comment by bamjam101** [comment]
It looks new and stunning, but I can suggest to add box-shadow to the menu so that it delivers a smooth scroll experience. Right now it feels too sharp for a menu.

Always love to check your work, good job.

**Comment by irffanasiff** [comment]
@kady-z assigning this to you add a button for join and use Inter front family from google fonts make sure events blogs about us and a button is there both on mobile view (don't use join button on hamburger mobile view)  and desktop view

**Comment by kady-z** [comment]
@demonicirfan There should be following Buttons: Events, Blogs , About Us and Join and Join should not be in navbar mobile view. Am I right?

**Comment by kady-z** [comment]
Thank you!.
