### ISSUE TITLE
Add a Footer to the website

### ISSUE THREAD

**Issue by irffanasiff** [demonicirfan/Hackrack.in#12]
It should look like this 
![image](https://user-images.githubusercontent.com/74172466/147869919-e1b473df-1772-49e1-9ced-97bbbef20c5e.png)
![image](https://user-images.githubusercontent.com/74172466/147869900-1e797cc6-d3e8-41b7-90b5-3e7493216201.png)

**Comment by Zoyakhatry1** [comment]
Hey ! Can you assign me this?

**Comment by sanket95droid** [comment]
I can do it..
Can you assign it plz??

**Comment by irffanasiff** [comment]
@Zoyakhatry1  was the first one to comment so I am assigning @sanket95droid i will assign you a new one

**Comment by sanket95droid** [comment]
Fine with me

**Comment by Zoyakhatry1** [comment]
Thank you @demonicirfan for assigning me this!
