### ISSUE TITLE
Make a Hero section for the webpage 

### ISSUE THREAD

**Issue by irffanasiff** [demonicirfan/Hackrack.in#3]
The hero section should look like this 

![image](https://user-images.githubusercontent.com/74172466/147040552-535d973c-e0f5-4db5-a922-e448c85eb0b7.png)
also have a look at [hackrack.in](hackrack.in) We have implement it over there. 

Gradient color - linear-gradient(270.1deg, #3783F6 0.1%, #02CBDE 41.42%, #5F0FCD 101.92%);
Font Family - [Inter](https://fonts.google.com/specimen/Inter)
Remember to make the button same as that on [hackrack.in](hackrack.in)

**Comment by khushi818** [comment]
Can you assign me this ?

**Comment by rohan-b-84** [comment]
Would you assign this to me ?
![Design - Active](https://user-images.githubusercontent.com/82886259/147061431-d2e1cf78-0334-47b9-9c13-3e0969f4ce4e.png)
![Design](https://user-images.githubusercontent.com/82886259/147061436-a5af7410-ca66-4403-a570-c082636dafee.png)

**Comment by irffanasiff** [comment]
Hii @rohan-b-84 and @khushi818 as khushi was the first one to comment so i will be assigning this to her and for you @rohan-b-84 i will assign you a new issue keep checking the issues section....

**Comment by irffanasiff** [comment]
@khushi818  you can also use this [prototype](https://www.figma.com/proto/rPhIkFFLjKnvmsONPnksql/Hackrack?node-id=2%3A12&scaling=min-zoom&page-id=0%3A1) for reference and [hackrack.in](hackrack.in) too. Do the necessary changes and i will review it whenever i am free.

**Comment by irffanasiff** [comment]
@rohan-b-84 check #7 and work with @khushi818 so that you both write less code(CSS). I hope you will collaborate with each other and try keeping the discussion below here.

**Comment by khushi818** [comment]
@demonicirfan Okay got it 👍thanks irfan
@rohan-b-84 I followed you on Twitter. You can message me. We can discuss if you want

**Comment by khushi818** [comment]
thanks @rohan-b-84 for helping me gradient and box-shadowing in button 
@demonicirfan I have send the pull request

**Comment by khushi818** [comment]
resolved @demonicirfan
